title: ''
title2: Mohammad Imrul Jubair
description: PhD student in Computer Science at the University of Colorado Boulder, working across AI, Visualization and HCI.
keywords: mohammad imrul jubair, AI, visualization, HCI, computer graphics, computer vision
url: https://imruljubair.github.io
baseurl:
repo: https://github.com/imruljubair/imruljubair.github.io
og_locale: en_US

author:
  name: Mohammad Imrul Jubair
  email: mohammad.jubair@colorado.edu
  url: https://imruljubair.github.io

markdown: kramdown
highlighter: rouge

sass:
  sass_dir: assets/scss
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
